// Generated by Wrangler on Wed Jul 03 2024 20:01:55 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: "local";
	SERVICE_NAME: "remix-drizzle-app-local";
	D1: D1Database;
}
